### ISSUE TITLE
showTime

### ISSUE THREAD

**Issue by 2WCSolutions** [Gillardo/ngx-bootstrap-datetime-popup#11]
Thank you very much for providing this.  I have a quick question.  When I saw showDate=true and showTime=false it does not seem to show the calendar at all.  If I hide the date and show the time it does show the time.  Am I doing something wrong?

Again, thank you!

**Comment by Gillardo** [comment]
Works fine for me.. can u replicate using plinker? Demo working for u??

**Comment by 2WCSolutions** [comment]
Let me recheck.  I am 100% sure this is some I have not done correctly.  I will get back to you and thanks for your response!

**Comment by 2WCSolutions** [comment]
I figured it out and it was my fault.  Very sorry to waste your time.

Thanks!!

**Comment by Gillardo** [comment]
lol, no worries.  I find that if i write for help, i usually find the solutio straight after, so it probably helped 😄
