### ISSUE TITLE
Is it possible to Add seconds to the Time picker ?

### ISSUE THREAD

**Issue by hamedtaha** [Gillardo/ngx-bootstrap-datetime-popup#12]
I use this component and I would like to know how to add seconds to the time picker

**Comment by Gillardo** [comment]
Is it possible with the normal ngx bootstrap timepicker?? I can't remember.. if it is possible there then I can do it

**Comment by hamedtaha** [comment]
it is here on this link https://valor-software.com/ngx-bootstrap/#/timepicker#toggleMinutesSeconds
I try to implement it

**Comment by Gillardo** [comment]
I may add a datepickeroptions and timepicker a class that u can pass in to set all the settings on each component

**Comment by hamedtaha** [comment]
that will be great
