### ISSUE TITLE
Faced issue in multiple accordion

### ISSUE THREAD

**Issue by alisamina0** [Gillardo/ngx-bootstrap-datetime-popup#13]
I am using multiple Accordion and used reactive form having name,description and datetime fields.

Can you please help me..

**Comment by Gillardo** [comment]
What's the issue? Can u replicate with plinker?

**Comment by Gillardo** [comment]
Plunkr. Lol

**Comment by alisamina0** [comment]
https://plnkr.co/edit/6hHyTuCHXygqn104kiGF?p=preview

Can you please help me.Thanks

**Comment by Gillardo** [comment]
but what is actually the problem???

**Comment by alisamina0** [comment]
Not able to bind the dateandtime field values and when i clicked on first datetimepicker, second datepicker also popup.
You can see in above plunker.

**Comment by alisamina0** [comment]
I am using bootstrap modal window for multiple Accordion and  each accordion contains  a form using *ngFor.
Please help.......

**Comment by Gillardo** [comment]
The opening of multiple datetimepickers at the same time, I would handle this by putting the datetimepicker into your own component, and hat have component decide when to open/close
