### ISSUE TITLE
What needs to be installed for ngx-bootstrap-datetime-popup

### ISSUE THREAD

**Issue by suchetaswabhav** [Gillardo/ngx-bootstrap-datetime-popup#14]
I have tried adding it in my module and component. But it says , Cannot find module 'ngx-bootstrap-datetime-popup' . What needs to be installed before this to ensure proper functioning

**Comment by suchetaswabhav** [comment]
npm install ngx-bootstrap-datetime-popup@1.2.7

**Comment by Gillardo** [comment]
yep, what does your module.ts file look like?  You looked at the demo?
