### ISSUE TITLE
About Past date

### ISSUE THREAD

**Issue by ankitvadi-bacancy** [Gillardo/ngx-bootstrap-datetime-popup#15]
Hello,

I am using this ngx-bootstrap-datetime-popup 
and its working fine in my website
but i want to hide the past date so any one can help to me that how to hide past date.
Is datetime Popup provide any option to hide past date ?
my code

<datetime-popup [value]="loanDate" [minDa]  (valueChange)="onValueChange($event)" [(showPopup)]="showPicker" [showDate]="showDate" [showTime]="showTime" [closeButton]="myCloseOptions"></datetime-popup>

**Comment by Gillardo** [comment]
cant hide dates, but you can disable dates using the normal ngx-bootstra datepicker, so you should just be able to pass the options into this component and it should do the same
