### ISSUE TITLE
New feature: Support showMeridian

### ISSUE THREAD

**Issue by Moulde** [Gillardo/ngx-bootstrap-datetime-popup#16]
Hi

I have been looking for a component which combines a datepicker and a timepicker in a nice way, and yours look really good.

It seems the timepicker has a flag that can be used to enable/disable the Meridian

    <timepicker [(ngModel)]="mytime" [showMeridian]="ismeridian"></timepicker>

It would be cool to be able to pass that setting out through your component.

Best regards

**Comment by Gillardo** [comment]
Why would you want to pass it out?  if you want to watch this variable, then you just need to make a service with a BehaviourSubject and subscribe to that...  Something like
```
@Injectable()
export class DateTimePickerComponentService {
    isMeridian: BehaviourSubject<boolean> = new BehaviourSubject<boolean>(false);
}
```
Then in your component where the datetime picker is, subscribe to this and set your variable, using ngInit
```
ngOnInit() {
    this.mySubscription = this.dateTimePickerComponentService.isMeridianSubject.subscribe((e) => this.isMeridian = e);
}
```
Remember to unsubscribe in ngOnDestroy

Now you have the ability to change the value via the component service which will in turn update the dateTimePicker component and you can watch it in other places.

Hope this helps?

**Comment by Moulde** [comment]
I'm not sure i understand.
My aim is to get access to the 'showMeridian' property when using your datetime-popup component.

With the service I would still have to inject it somewhere i can access the 'showMeridian' property, right?

By passing it out, I mean the following.

    <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                                    [(showPopup)]="showPicker"
                                    [showDate]="showDate"
                                    [showTime]="showTime"
                             ---->  [showMeridian]="false"
                                    [closeButton]="closeButton"
                                    ></datetime-popup>

**Comment by Gillardo** [comment]
this is the same as accessing the property of the datetime-popup.  The property can only be set by a variable, so if you create the service, you are creating a watchable variable.

Your component below would then use that variable to set isMeridian.
```
<datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                                [(showPopup)]="showPicker"
                                [showDate]="showDate"
                                [showTime]="showTime"
                         ---->  [showMeridian]="isMeridian"
                                [closeButton]="closeButton"
                                ></datetime-popup>
```

**Comment by Gillardo** [comment]
Yes you would have to inject the the service, but this is fine, because when i use the datetime-popup in my code, i create a date input field, which has the datetime popup within it.  That way the service is only injected into that component.  If you really wanted, you could have an output/input property for isMeridian on your component.

**Comment by Gillardo** [comment]
By creating my own date component to be used in my project, it also means that if i change the datetime popup, its only done in one place and rippled throughout my application

**Comment by Moulde** [comment]
I may very well have a case of the mondays..

But if the datetime-popup component doesn't give me access to set the 'showMeridian' property on it's child component, then how can I access it?

In your DateComponent, how would you go and set the 'showMeridian' property?

**Comment by Gillardo** [comment]
I am sorry, it looks like its a case of the Mondays for me!  Sorry been a mental weekend and morning.  I will add this for you 😄

**Comment by Gillardo** [comment]
All done... available in 3.2.5...

Sorry again for being stupid 😆

**Comment by Moulde** [comment]
Haha, no worries :)
That's perfect, thank you Gillardo!

Although not relevant to this, thank you for the samples anyway, it looks really clean!

**Comment by Moulde** [comment]
Do you by any chance have the source for InputUtils as well?

**Comment by Gillardo** [comment]
oooo pushing it 😆 

```
import { Injectable } from '@angular/core';

@Injectable()
export class InputUtils {

    pad(n): string {
        const width = 2;
        const z = '0';
        n = n + '';

        return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;
    }

    dateToString(val: Date, showDate: boolean, showTime: boolean): string {
        if (!val || val == null) {
            return '';
        } else {
            const date = new Date(val);
            let str = '';

            if (showDate) {
                str = this.pad(date.getDate()) + '/'
                    + this.pad((date.getMonth() + 1)) + '/'
                    + date.getFullYear();

                if (showTime) {
                    str += ' ';
                }
            }

            if (showTime) {
                str += this.pad(date.getHours()) + ':' + this.pad(date.getMinutes());
            }

            return str;
        }
    }

    getDateParts(val: string, showDate: boolean, showTime: boolean, autoFormat: boolean): any {
        let parts = [];

        if (val == '' || val.length < 5) {
            return null;
        } else {
            const date = new Date();
            let year = '';
            let month = '';
            let day = '';
            let hour = '';
            let minute = '';

            if (showDate) {
                parts = showTime && val.indexOf(' ') > -1 ? val.substring(0, val.indexOf(' ')).split('/') : val.split('/');

                if (parts.length >= 2) {
                    if (autoFormat && +parts[ 2 ] < 1900) {
                        const yearAsNumber = +parts[ 2 ];
                        year = ((yearAsNumber > 60 ? 1900 : 2000) + yearAsNumber).toString();
                    } else {
                        if (parts[ 2 ].length >= 2) {
                            year = parts[ 2 ];
                        }
                    }
                }

                if (parts.length > 1) {
                    if (parts[ 1 ].length == 2) {
                        month = parts[ 1 ];
                    }
                }

                if (parts.length > 0) {
                    if (parts[ 0 ].length == 2) {
                        day = parts[ 0 ];
                    }
                }

                if (!showTime || autoFormat) {
                    hour = '00';
                    minute = '00';
                }
            }

            if (showTime && val.indexOf(':') > -1) {
                parts = showDate && val.indexOf(' ') > -1 ? val.substring(val.indexOf(' ') + 1).split(':') : val.split(':');

                if (parts.length > 0 && parts[ 0 ].length > 1) {
                    hour = parts[ 0 ];
                }

                if (parts.length > 1 && parts[ 1 ].length > 1) {
                    minute = parts[ 1 ];
                }

                if (!showDate) {
                    year = date.getFullYear().toString();
                    month = date.getMonth().toString();
                    day = date.getDate().toString();
                }
            }

            if (year == '' || month == '' || day == '' || hour == '' || minute == '') {
                return null;
            } else {
                return {
                    year,
                    month,
                    day,
                    hour,
                    minute
                };
            }
        }
    }

    partsToDate(parts: any, showDate: boolean, showTime: boolean): Date {
        if (parts == null) {
            return null;
        } else if (parts.year < 1900) {
            return null;
        } else {
            const date = new Date();

            date.setFullYear(parseInt(parts.year, 10), parseInt(parts.month, 10) - 1, parseInt(parts.day, 10));
            date.setHours(parseInt(parts.hour, 10), parseInt(parts.minute, 10), 0, 0);

            return date;
        }
    }

    stringToDate(val: string, showDate: boolean, showTime: boolean): Date {
        const parts = this.getDateParts(val, showDate, showTime, false);

        return this.partsToDate(parts, showDate, showTime);
    }
}
```

I did wonder about releasing this as a component, cos its very handy and i use it in a lot of projects
