### ISSUE TITLE
Peer Dependency Issue

### ISSUE THREAD

**Issue by NTXAggie** [Gillardo/ngx-bootstrap-datetime-popup#17]
Package "ngx-bootstrap-datetime-popup" has an incompatible peer dependency to "@angular/forms" (requires "^4.0.0" (extended), would install "7.2.1").

**Comment by Gillardo** [comment]
works on my application and i am using angular 7.1.1....

**Comment by NTXAggie** [comment]
I was also on 7.1.1 ..... I was trying to update to the latest 7.2.1

**Comment by Gillardo** [comment]
i will be updating my project today or tomorrow, so let me try that and see if happens to me

**Comment by Gillardo** [comment]
seems this is all fine.  i have updated my project and not got issues?

**Comment by Gillardo** [comment]
closed as no response
