### ISSUE TITLE
No provider for ComponentLoaderFactory

### ISSUE THREAD

**Issue by Ulyanca99** [Gillardo/ngx-bootstrap-datetime-popup#26]
Hello,
I have the same problem that https://github.com/Gillardo/ngx-bootstrap-datetime-popup/issues/19 but, i'm using ngx-bootstrap@5.1.0 and ngx-bootstrap-datetime-popup@5.0.2.

ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[BsDropdownDirective -> ComponentLoaderFactory]: 
  StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
Error: NullInjectorError: No provider for ComponentLoaderFactory!

My app.module :
@NgModule({
    imports: [
        BrowserAnimationsModule,
        BrowserModule,
        CoreModule,
        SharedModule,

        AppRoutingModule,

        BsDropdownModule.forRoot(),
        DatepickerModule.forRoot(),
        TimepickerModule.forRoot(),
        DatetimePopupModule.forRoot()
    ],
...})

**Comment by 9you** [comment]
You can try to update to
`"ngx-bootstrap": "~5.2.0",`

**Comment by Gillardo** [comment]
I am currently using 5.0.2 with ngx-bootstrap@5.3.2 and all is fine.  Can you make a plunkr to replicate if you cant upgrade to later version?  i would try 5.2.0 minimum and see if that sorts problem

**Comment by Gillardo** [comment]
Did you update to later version> did that sort your problem out?

**Comment by Gillardo** [comment]
Please install the latest version which has been reworked.  I have also added a note to the README file to help with this
