### ISSUE TITLE
Plunker demo

### ISSUE THREAD

**Issue by maciej-laskowski** [Gillardo/ngx-bootstrap-datetime-popup#28]
Hi!

The Plunker demo linked in Readme.md doesn't work, throws a bunch of 404 in the console.

**Comment by Gillardo** [comment]
Plunkr was a right pain, so since i have a demo site on github i have moved this to github pages.  Should be available now at https://gillardo.github.io/ngx-bootstrap-datetime-popup/

Only a very simple demo at the moment, happy to add more to it
