### ISSUE TITLE
Can I change text to buttons?

### ISSUE THREAD

**Issue by andretmn** [Gillardo/ngx-bootstrap-datetime-popup#3]

**Comment by Gillardo** [comment]
what you mean?  What text to buttons?

**Comment by andretmn** [comment]
There are 'Clear', 'Now', 'Close' buttons on timepicker
I want to change the text to 'Blah' for example

**Comment by andretmn** [comment]
I have edited your plugin localy(not the best idea) to
<li class=\"mx-2 mb-2\">\n\
                                    <span class=\"btn-group pull-left\">\n\
                                      <button class=\"btn btn-secondary btn-sm\" (click)=\"onNow()\">{{nowBtnText}}</button>\n\
                                      <button class=\"btn btn-secondary btn-sm\" (click)=\"onClear()\">{{clearBtnText}}</button>\n\
                                      <button class=\"btn btn-secondary btn-sm\" (click)=\"offClick()\">{{closeBtnText}}</button>\n\
                                    </span>\n\
                                   </li>\n\

Where {{nowBtnText}}, {{clearBtnText}} and {{closeBtnText}} are params to customize the labels

**Comment by Gillardo** [comment]
yep, i did all this sort of thing in the old angular1 version [here](https://github.com/Gillardo/bootstrap-ui-datetime-picker).

But because this was created for work, i didnt need all those options at the moment, so never added them.

**Comment by andretmn** [comment]
whene I make
> ng build --prod

I receive the following error:
ERROR in Unexpected value 'DatetimePopupModule in C:/Users/andre/Projects/MgarEranitApp/node_modules/ngx-bootstrap-datetime-popup/lib/datetime-popup.module.d.ts' imported by the module 'AppModule in C:/Users/andre/Projects/MgarEranitApp/src/app/app.module.ts'. Please add a @NgModule annotation.
ERROR in ./src/main.ts
......

do you have an idea how can i solve it?

**Comment by Gillardo** [comment]
Sorry but i do not use ng-build, i use webpack.  If however you can create a basic project using ng-build and upload it here, i can download and see if i can sort it for you??

**Comment by Gillardo** [comment]
@andretmn do you get this with the latest version now?

**Comment by Gillardo** [comment]
I have changed this in version 1.1.0 for you.  You can now configure the labels, whether a button is shown or not and also state the cssClass to use for each button.  Hope this helps
