### ISSUE TITLE
ModuleWithProviders type without a generic type argument

### ISSUE THREAD

**Issue by MeMeBigProgrammer** [Gillardo/ngx-bootstrap-datetime-popup#35]
In order for this library to be compatible for Angular 9, `ModuleWithProviders` requires a generic argument. 

More can be read [here](https://angular.io/guide/migration-module-with-providers)

**Comment by syedyawar** [comment]
Please fix and update this on npm

**Comment by Gillardo** [comment]
This is already done I just need to do one last thing before uploading it to npm

**Comment by Gillardo** [comment]
But the library still works with angular 9 as I am using it in my project running angular 9.1.0 and it works fine

**Comment by syedyawar** [comment]
> But the library still works with angular 9 as I am using it in my project running angular 9.1.0 and it works fine

I'm on angular 9.1.3,
at first, i'm having the same error, but then I remove and again install this package and boom,error gone

**Comment by MeMeBigProgrammer** [comment]
seems like @Gillardo fixed and merged this, so I'll close this.

**Comment by Gillardo** [comment]
I have fixed it, but i cant publish it atm because i cannot get the gh-pages command to work to create the demo site on github
