### ISSUE TITLE
Not working in Angular 9

### ISSUE THREAD

**Issue by fzs1994** [Gillardo/ngx-bootstrap-datetime-popup#37]
Just a blank space, no elements are getting created inside the component.

![image](https://user-images.githubusercontent.com/10684213/83253760-29351880-a1cb-11ea-85b6-8a038dc5a410.png)

**Comment by Gillardo** [comment]
works fine in angular9, i am using it.  have you included everything in your app.module.ts file?

**Comment by fzs1994** [comment]
I've created a shared module where I did all imports properly. Still not working. Can you please share Stackblitz of your working code pls?

**Comment by fzs1994** [comment]
I'll share a stackblitz url shortly.

**Comment by Gillardo** [comment]
share your url and will have a look for you

**Comment by fzs1994** [comment]
There is some issue installing ngx-bootstrap on stackblitz

**Comment by Gillardo** [comment]
you sorted your issue?

**Comment by Gillardo** [comment]
download the demo in the project if you need to see an example?

**Comment by fzs1994** [comment]
Yeah man. Sorted out. Thanks!
