### ISSUE TITLE
 ERROR in node_modules/ngx-bootstrap-datetime-popup/node_modules/@angular/core/core.d.ts(7414,55): error TS1005: ']' expected. node_modules/ngx-bootstrap-datetime-popup/node_modules/@angular/core/core.d.ts(7414,57): error TS1134: Variable declaration expected. node_modules/ngx-bootstrap-datetime-popup/node_modules/@angular/core/core.d.ts(7414,116): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by enigma49** [Gillardo/ngx-bootstrap-datetime-popup#46]
Hello all, I am getting this error when I installed an run it. Please help me out.

    "ngx-bootstrap": "^2.0.5",
    "ngx-bootstrap-datetime-popup": "^6.0.0", 
    Angular CLI: 7.3.10

**Comment by Gillardo** [comment]
you need to upgrade ngx-bootstrap to v6+

**Comment by enigma49** [comment]
I changed the files to this 
"ngx-bootstrap": "^5.2.0",
"ngx-bootstrap-datetime-popup": "^5.0.2", 

and now I am facing this issue, do I have to set both of them to same a version? 
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[BsDropdownDirective -> ComponentLoaderFactory]:
StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]:
NullInjectorError: No provider for ComponentLoaderFactory!
Error: NullInjectorError: No provider for ComponentLoaderFactory!

**Comment by Gillardo** [comment]
I believe you still have the wrong versions.... you may want to delete node_modules folder and run `npm i` to make sure node_modules is all correct.  Check if you have a node_modules folder with the ngx-bootstrap-datetime-popup folder.  If you do, the components that are in there do not match the versions in your project

**Comment by enigma49** [comment]
I just made changes and I am getting this error
WARNING in ./node_modules/ngx-bootstrap-datetime-popup/node_modules/@angular/core/fesm2015/core.js 28600:15-102
Critical dependency: the request of a dependency is an expression

I made sure to keep ngx-bootstrap's version same in app and in ngx-bootstrap-datetimepopu's package.json
    "ngx-bootstrap": "^5.2.0",
    "ngx-bootstrap-datetime-popup": "^6.0.0",

**Comment by Gillardo** [comment]
That isnt right, because ngx-bootstrap-datetime-popup@6.0.0 uses ngx-bootstrap 6.0.0+ and you have verison 5.2.0

**Comment by enigma49** [comment]
should I change ngx-bootstrap to 6.1.0 and check?

**Comment by enigma49** [comment]
I can also use ngx-bootstrap-datetime-popup@5.0.0+ with my current version of ngx-bootstrap right?

**Comment by Gillardo** [comment]
Yes or at least to ^6.0.0

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Gillardo** [comment]
what is your current version of ngx-bootstrap?

**Comment by enigma49** [comment]
okay, actually I don't think I am supposed to change the current version of ngx-bootstrap, so i will try to use ngx-bootstrap-datetimepopup@5.1.0

**Comment by enigma49** [comment]
cuurently I am using "ngx-bootstrap": "^5.2.0",

**Comment by Gillardo** [comment]
So you need to use 5.1.0 of ngx-bootstrap-datetime-popup

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by enigma49** [comment]
okay, I will try that

**Comment by enigma49** [comment]
I changed versions to     
```
"ngx-bootstrap": "^5.2.0",
"ngx-bootstrap-datetime-popup": "^5.1.0",
```
I even changed the ngx-bootstrap in ngx-bootstrap-datetime-popup's package.json to "^5.2.0",
but now I am getting these errors 

in terminal:
WARNING in ./node_modules/ngx-bootstrap-datetime-popup/node_modules/@angular/core/fesm5/core.js 29284:15-102
Critical dependency: the request of a dependency is an expression

in console:
```
CompanySendEmailGpmsComponent.html:110 ERROR Error: StaticInjectorError(AppModule)[DatetimePopupComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[DatetimePopupComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8896)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveNgModuleDep (core.js:21218)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
    at resolveNgModuleDep (core.js:21218)
View_CompanySendEmailGpmsComponent_1 @ CompanySendEmailGpmsComponent.html:110
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
(anonymous) @ core.js:18126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18126
(anonymous) @ core.js:18010
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:385
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
next @ core.js:18010
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
checkStable @ core.js:17268
onLeave @ core.js:17335
onInvokeTask @ core.js:17293
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1708
CompanySendEmailGpmsComponent.html:110 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 71, nodeDef: {…}, elDef: {…}, elView: {…}}
View_CompanySendEmailGpmsComponent_1 @ CompanySendEmailGpmsComponent.html:110
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15777
(anonymous) @ core.js:18126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18126
(anonymous) @ core.js:18010
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:385
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
next @ core.js:18010
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:195
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:133
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
checkStable @ core.js:17268
onLeave @ core.js:17335
onInvokeTask @ core.js:17293
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1708
CompanySendEmailGpmsComponent.html:110 ERROR TypeError: Cannot read property 'instance' of undefined
    at nodeValue (core.js:21780)
    at Object.eval [as handleEvent] (CompanySendEmailGpmsComponent.html:110)
    at handleEvent (core.js:23107)
    at callWithDebugContext (core.js:24177)
    at Object.debugHandleEvent [as handleEvent] (core.js:23904)
    at dispatchEvent (core.js:20556)
    at core.js:21003
    at platform-browser.js:993
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:17290)
```

**Comment by Gillardo** [comment]
What version of angular are you using?

**Comment by enigma49** [comment]
`Angular CLI: 7.3.10`

**Comment by Gillardo** [comment]
what about @angular/core??

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by enigma49** [comment]
I am still new to angular, I ran ng v and this was the output
`@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@angular/material                 7.3.7
@angular/pwa                      0.6.8
@ngtools/webpack                  7.0.7
@schematics/angular               0.6.8
@schematics/update                0.13.10
rxjs                              6.2.2
typescript                        3.1.6
webpack                           4.19.1`

**Comment by enigma49** [comment]
```
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.10
@angular/material                 7.3.7
@angular/pwa                      0.6.8
@ngtools/webpack                  7.0.7
@schematics/angular               0.6.8
@schematics/update                0.13.10
rxjs                              6.2.2
typescript                        3.1.6
webpack                           4.19.1
```

**Comment by Gillardo** [comment]
this isnt a new project is it?  Cos your version numbers are way off what i
would expect.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Gillardo** [comment]
![image](https://user-images.githubusercontent.com/7406381/98937380-3aa28080-24de-11eb-8698-f5415fe23560.png)

**Comment by Gillardo** [comment]
![image](https://user-images.githubusercontent.com/7406381/98937473-5a39a900-24de-11eb-8424-053e31a9d49f.png)

**Comment by enigma49** [comment]
it's an old project I am an sde trainee and I have been tasked with a new page where I need your plugin

**Comment by Gillardo** [comment]
yeah your project is very very old.....

what version of ngx-bootstrap where you running at first before upgrading it all?

**Comment by Gillardo** [comment]
Oh i see, v2.0.5

**Comment by enigma49** [comment]
2.0.5

**Comment by Gillardo** [comment]
If you dont include my plugin and you update ngx-bootstrap to ^3.0.0 does
that all work for you?

If it does, then maybe you just want to do that and install version 3.0.0
of this plugin which is compatible with ngx-bootstrap 3.0.0 and see if that
works?

**Comment by enigma49** [comment]
okay let me try that.

**Comment by Gillardo** [comment]
Ok, i am off out for a few hours so will reply when back

**Comment by enigma49** [comment]
okay, thanks really appreciate your help

**Comment by enigma49** [comment]
![image](https://user-images.githubusercontent.com/25546856/98940710-668b2980-2511-11eb-9143-dc6c8d0cc5bc.png)

I changed both versions to 3.0.0, I don't see any errors now but I don't see the input field either

**Comment by Gillardo** [comment]
What does the HTML look like for it?

**Comment by enigma49** [comment]
```
                                            <div class="form-group row">

                                                <label id="label" for="datetimepicker" class="col-md-4">Scheduled At <span
                                                    style="color: salmon">*</span></label>
                                                    <div class="container">
                                                        <div class="row">
                                                           <div class='col-sm-6'>
                                                              <div class="form-group" id="datetimepicker">
                                                                <datetime-popup [(value)]="myDate"></datetime-popup>
                                                              </div>
                                                           </div>
                                                        </div>
                                                     </div>

                                            </div>
```

**Comment by Gillardo** [comment]
What elements can you see are rendered when the page is built via the
console Dev tools?

**Comment by Gillardo** [comment]
If you comment out the popup component does the html appear on the web page?

**Comment by enigma49** [comment]
![image](https://user-images.githubusercontent.com/25546856/99046689-1ff10a00-25b9-11eb-8c6b-72627d219626.png)

**Comment by enigma49** [comment]
this is what I see in the elements

**Comment by Gillardo** [comment]
Minimise datetime-popup, so can see more....

I am guessing your input is in the HTML?  Just wonder why cant see it.....

**Comment by enigma49** [comment]
![image](https://user-images.githubusercontent.com/25546856/99057599-07392200-25c2-11eb-8aa5-1c9f4375bbc2.png)

**Comment by Gillardo** [comment]
You havent added a text box to show the date?

**Comment by enigma49** [comment]
No I just have to take the inputs and store it in the database

**Comment by enigma49** [comment]
```
<div class="form-group row">

                                                <label id="label" for="datetimepicker" class="col-md-4">Scheduled At <span
                                                    style="color: salmon">*</span></label>
                                                    <div class="container">
                                                        <div class="row">
                                                           <div class='col-sm-6'>
                                                              <div class="form-group" id="datetimepicker">
                                                                <datetime-popup [(value)]="myDate"></datetime-popup>
                                                              </div>
                                                           </div>
                                                        </div>
                                                     </div>

                                            </div>

```

This is how I am using it on the html side

**Comment by Gillardo** [comment]
Then you need to add a button or something to press so you can open the date picker

**Comment by enigma49** [comment]
I didn't find anything like that in the docs, could you please show me how?

**Comment by Gillardo** [comment]
Have you even looked at the demo pages or the readme?

**Comment by enigma49** [comment]
https://plnkr.co/edit/nYNzcgXd9Wz8pxMsPY29?preview I am currenlty refering to this one

**Comment by enigma49** [comment]
I found this in the docs of 3.0.0

**Comment by Gillardo** [comment]
The readme file also shows u an example.

**Comment by enigma49** [comment]
Hi, I made the changes in my code as given here https://plnkr.co/edit/nYNzcgXd9Wz8pxMsPY29?preview  still I am not able to see anything on my display

this is the html I am using

```
                                                     <div class="col-sm-6">
                                                        <div class="input-group">
                                                            <input class="form-control" [(ngModel)]="myDate" />
                                                            <span class="input-group-btn">
                                                                <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                                                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                                                </button>
                                                            </span>
                                                        </div>
                                                        <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                                                                        [(showPopup)]="showPicker"
                                                                        [showDate]="showDate"
                                                                        [showTime]="showTime"
                                                                        [closeButton]="closeButton"
                                                                        >
                                                        </datetime-popup>
                                                     </div>
```

**Comment by enigma49** [comment]
Hey! Thank you so much for your help I managed to solve the issue. i really appreciate you taking time out of your busy schedule to help. Thanks Again!

**Comment by Gillardo** [comment]
No worries.

**Comment by enigma49** [comment]
Hi just a quick question is there a way to select stepMinutes? like set stepMinutes of 15 mins

**Comment by Gillardo** [comment]
You may want to check the parameters that the component takes on here.  Yes minuteStep is an input parameter and defaults to 5

**Comment by enigma49** [comment]
okay thanks, and also thanks for being so patient. I know I might have had some dumb questions.
