### ISSUE TITLE
TypeError: date1.getFullYear is not a function

### ISSUE THREAD

**Issue by juchen0429** [Gillardo/ngx-bootstrap-datetime-popup#5]
Hi Gillardo,

When I input, this is the problem。

ERROR Error: Uncaught (in promise): TypeError: date1.getFullYear is not a function
TypeError: date1.getFullYear is not a function

**Comment by Gillardo** [comment]
Are u using latest release??

**Comment by juchen0429** [comment]
yes。

**Comment by juchen0429** [comment]
html：
<div class="row form-group">
        <div class="col-md-6">
            <div class="input-group">
                <input class="form-control" [(ngModel)]="myDate" />
                <span class="input-group-btn">
                    <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
            <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                            [(showPopup)]="showPicker"
                            [showDate]="showDate"
                            [showTime]="showTime"></datetime-popup>
        </div>
    </div>

Do I lack some parameters?

**Comment by juchen0429** [comment]
html：
<div class="row form-group">
        <div class="col-md-6">
            <div class="input-group">
                <input class="form-control" [(ngModel)]="myDate" />
                <span class="input-group-btn">
                    <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
            <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                            [(showPopup)]="showPicker"
                            [showDate]="showDate"
                            [showTime]="showTime"></datetime-popup>
        </div>
    </div>

Do I lack some parameters?

**Comment by juchen0429** [comment]
<div class="row form-group">
        <div class="col-md-6">
            <div class="input-group">
                <input class="form-control" [(ngModel)]="myDate" />
                <span class="input-group-btn">
                    <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
            <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                            [(showPopup)]="showPicker"
                            [showDate]="showDate"
                            [showTime]="showTime"></datetime-popup>
        </div>
    </div>

**Comment by juchen0429** [comment]
div class="row form-group">
        <div class="col-md-6">
            <div class="input-group">
                <input class="form-control" [(ngModel)]="myDate" />
                <span class="input-group-btn">
                    <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                    </button>
                </span>
            </div>
            <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                            [(showPopup)]="showPicker"
                            [showDate]="showDate"
                            [showTime]="showTime"></datetime-popup>
        </div>
    </div
Do I lack some parameters?

**Comment by Gillardo** [comment]
Can you put this on plunkr or something so i can run it for you and check if ok?

**Comment by Gillardo** [comment]
What does your .ts controller look like?

**Comment by Gillardo** [comment]
@juchen0429 fork this plunkr for me and change the code as you have it.

https://plnkr.co/edit/nYNzcgXd9Wz8pxMsPY29

**Comment by Gillardo** [comment]
@juchen0429 I have found your issue and updated the code for you.  v1.2.1 is now released which fixes the issue.

Also released a demo on the above plunkr
