### ISSUE TITLE
Issue with contents of npm package for v7.0.0

### ISSUE THREAD

**Issue by jethas-bennettjones** [Gillardo/ngx-bootstrap-datetime-popup#62]
Hi @Gillardo,

Thanks for pushing out v7. I noticed, though, that the contents is of the main folder and not of the dist folder, which is what I was expecting. Would you be able to republish this, but with the contents of the dist folder only?

**Comment by Gillardo** [comment]
I will have a look later today for you

**Comment by Gillardo** [comment]
it seems that the changes made by the PR have broken the publishing... the files in package.json like "main", "module" dont exist

**Comment by jethas-bennettjones** [comment]
I'm not sure what to say about this as I've never needed to set these properties up, even for a full Angular application.
I've created a new branch that fixes a compilation issue, but when I run this command it gets all the way to publishing to npm before failing:
```
npm run build -- --configuration production
cd dist
npm publish
```

**Comment by Gillardo** [comment]
You cant publish to npm as you are not the owner

Also when builiding, its not doing partial mode
![image](https://user-images.githubusercontent.com/7406381/146411633-20ff1028-2734-4a3a-8d73-37564c8d5722.png)

**Comment by Gillardo** [comment]
I have changed the code and published to npm version 7.0.1

Can you see if this is now right for me please?

**Comment by jethas-bennettjones** [comment]
> You cant publish to npm as you are not the owner
> 
> Also when builiding, its not doing partial mode ![image](https://user-images.githubusercontent.com/7406381/146411633-20ff1028-2734-4a3a-8d73-37564c8d5722.png)

Yes, that makes sense. I just wanted to make sure that we were both following the same commands up until publishinging.
I had changed the compilation mode in my PR. Have you tried it after merging that in?

**Comment by Gillardo** [comment]
i run the command `npm run build` which isnt setting the configuration.  I have now set a "default" configuration when running the build command, so that should sort it.

Did it work when you download via npm now?

**Comment by jethas-bennettjones** [comment]
Hi @Gillardo.
Thanks for sorting that out, though I think there's still an issue with the wrong directory being packaged.
Here is a screenshot of the package I build from the dist folder that contains the module folders at the top level, and works as expected:
![image](https://user-images.githubusercontent.com/62298251/146464184-b54a4689-28e1-4c7f-a9a8-a398960f696e.png)
And here is the contents of v7.0.1 found on npmjs.org, where you can see that all of the module folders are one level deeper:
![image](https://user-images.githubusercontent.com/62298251/146464875-9eb15b60-c1d2-4bc0-93da-cfb59116d66e.png)

I think that, if you run `npm publish` from the dist folder after the package is built, that should sort this out.

**Comment by Gillardo** [comment]
Please try again.  

The reason the error was occuring is that in this change, the version number was removed.  This is needed for npm packaging

https://github.com/Gillardo/ngx-bootstrap-datetime-popup/commit/7dfb77333e950a89473cc60fc5a1d0b3197dca52#diff-a79278fd3642e896ac2cc5d77d4be16dae1270fc660a87a5e383f588b32bab24

Can you have a look now please.  I have also added a npm script for publishing to npm as its been a while for me as well lol

**Comment by jethas-bennettjones** [comment]
Thanks for updating this. The package structure looks good. I'll test it out today and log a ticket if I'm still having issues.
