### ISSUE TITLE
How to change the date format on page loads

### ISSUE THREAD

**Issue by saravananNV** [Gillardo/ngx-bootstrap-datetime-popup#7]
while the page loads . i need to change the date format  like date/month/year . how to achieve that

**Comment by Gillardo** [comment]
change the format on what?  the date picker is a separate component to your input box/html element.  You can do this how you like.  If you want to add a plunkr, i can look at it for you to help?

**Comment by saravananNV** [comment]
![datepicker](https://user-images.githubusercontent.com/4658026/33713981-59120192-db73-11e7-868e-7df7e7696f06.png)
is this will be helpful for you ?

**Comment by Gillardo** [comment]
Yeah this is nothing to do with the datepicker, as its your input.  You may want to look at https://github.com/text-mask/text-mask which i use to format my inputs.  I wrote a separate component that i use throughout my site.  If you want i can upload the code here for you to work with

**Comment by Gillardo** [comment]
if you do not want the users to type the date, you could also use a `div` element and then use `{{ yourdate | date:'YOUR FORMAT' }}`

**Comment by saravananNV** [comment]
Hey..Thanks ..@Gillardo. .i tried that pipe .its throwing error..let me try your code.can you please post it here.

**Comment by Gillardo** [comment]
pipe i sent you was invalid, as i didnt use correct format.  I have uploaded example here to use div

https://plnkr.co/edit/5BwTrwurN3vdx92FjRzb?p=preview

**Comment by saravananNV** [comment]
@Gillardo  ..Thanks for the quick comments and reply..you are one of the good contributor that i ever met on github.. i make it work on assigning that format  which we want on page load itself.. 

works like charm...thanks for your date picker..its amazing ...keep your sprits UP...

**Comment by Gillardo** [comment]
No problem! 👍
