### ISSUE TITLE
Not showing popup only.

### ISSUE THREAD

**Issue by vibhoo** [Gillardo/ngx-bootstrap-datetime-popup#8]
Hi! Gillardo, I have implemented this ngx-bootstrap-datetime-popup, according to the documentation but it's now showing up. However, the when I inspect the elements its show ng-reflect-show-popup= true
Can you please help me with this?

**Comment by Gillardo** [comment]
Can you create a quick plunkr or i am shooting in the dark really?  Or at least give me the html and .ts you got?

**Comment by vibhoo** [comment]
In my module.ts i'm using ,`import { DatetimePopupModule } from 'ngx-bootstrap-datetime-popup';`
and imported `DatetimePopupModule.forRoot(),` in my imports
In HTML
`<div class="input-group">
                        <input class="form-control" [(ngModel)]="myDate" name="date" />
                        <span class="input-group-btn">
                            <button class="btn btn-outline-secondary" (click)="onTogglePicker()">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                            </button>
                        </span>
                    </div>
                    <datetime-popup [value]="myDate" (valueChange)="onValueChange($event)"
                                    [(showPopup)]="showPicker"
                                    [showDate]="showDate"
                                    [showTime]="showTime"
                                    [closeButton]="closeButton"
                                    ></datetime-popup>
`

**Comment by Gillardo** [comment]
stupid question.... but u got bootstrap included?
Can you replicate it on a plunkr?  I find it usually helps

**Comment by vibhoo** [comment]
Yes! I have included, bootstrap and ngx-bootstrap also. The problem is I can't create plunkr because the project is to big and using other dependencies also.

**Comment by Gillardo** [comment]
fork the demo plunkr and change the html and typescript to match yours.

**Comment by vibhoo** [comment]
Okay! I'll do that but I have followed exactly the same process as you have mentioned in the demo plunkr. Infact I copy-pasted everything.

**Comment by Gillardo** [comment]
anything??

**Comment by vibhoo** [comment]
I have followed exact demo plunkr. So I don't know what to change in it. Have you included any additional library ? I'm using Bootstrap 3

**Comment by Gillardo** [comment]
that could be your problem! i am using bootstrap 4... i will try bootstrap 3 shortly

**Comment by vibhoo** [comment]
Please share your feedback here after using bootstrap 3

**Comment by vibhoo** [comment]
any update ?

**Comment by Gillardo** [comment]
Here is a plunkr with bootstrap 3.  as you can see it works fine. https://plnkr.co/edit/v67eawnhgjSNtcHcGbaP?p=preview

If you want to change it to replicate your error and then want me to look thats fine.

What version of ngx-bootstrap are you referencing??

**Comment by Gillardo** [comment]
Did you have any luck with this?  Did you try the plunkr?

**Comment by vibhoo** [comment]
No luck. Closing the issue, for now, will try to work on it later and will let you know. Thanks for your time.

**Comment by Gillardo** [comment]
I have done changes to this project since u reported it so u may want to update to latest to
